# Generated by Django 4.2.23 on 1979-12-31 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.CharField(default=datetime.datetime(1979, 12, 31, 23, 26, 12, 223131, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
