# Generated by Django 4.2.23 on 1979-12-31 23:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('street', '0003_card'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='FrontCard',
        ),
    ]
