# Generated by Django 4.2.23 on 2025-07-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street', '0009_chatmessage_remove_message_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpaymentinfo',
            name='message',
        ),
        migrations.AddField(
            model_name='userpaymentinfo',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
