# Generated by Django 4.2.23 on 2025-08-03 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('street', '0010_remove_userpaymentinfo_message_userpaymentinfo_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
